fix(patch): initialize semver for terraform

diff --git a/.github/workflows/tf-deploy.yml b/.github/workflows/tf-deploy.yml
--- a/.github/workflows/tf-deploy.yml
+++ b/.github/workflows/tf-deploy.yml
@@ -3,10 +3,6 @@ name: Deploy on Tag
 on:
   workflow_dispatch:
     inputs:
-      tag:
-        description: 'The version tag to deploy'
-        required: true
-        type: string
       environment:
         description: 'Environment to deploy to'
         required: true
@@ -34,13 +30,23 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Validate tag pattern
+        shell: bash
+        run: |
+          if [[ ! "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Tag ${{ github.ref_name }} does not match the required pattern vX.X.X (e.g., v1.0.0). Please make sure you've selected workflow source as tags instead of branches."
+            exit 1
+          else
+            echo "Tag name ${{ github.ref_name }} is valid"
+          fi
+
       - name: Set environment vars
         shell: bash
         run: |
-          if [[ ${{inputs.tag}} == 'dev' ]]; then
+          if [[ ${{inputs.environment}} == 'dev' ]]; then
               echo "AWS_ROLE=arn:aws:iam::949263681218:role/milan-splittr-terraform-github-action-write-role" >> $GITHUB_ENV
               echo "ENV=dev" >> $GITHUB_ENV
-          elif [[ ${{inputs.tag}} == 'prod' ]]; then
+          elif [[ ${{inputs.environment}} == 'prod' ]]; then
               echo "AWS_ROLE=arn:aws:iam::949263681218:role/milan-splittr-terraform-github-action-write-role" >> $GITHUB_ENV
               echo "ENV=prod" >> $GITHUB_ENV
           fi
@@ -60,7 +66,7 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.event.inputs.tag }}
+          ref: ${{ github.ref_name }}
       
       - name: Add github safe dir
         run: git config --global --add safe.directory /__w/terraform-code/terraform-code
@@ -75,12 +81,12 @@ jobs:
       - name: Init
         id: init
         run: |
-          cd terraform/environments/${{inputs.tag}}
+          cd terraform/environments/${{inputs.environment}}
           terraform init
 
       - name: Apply
         if: ${{steps.init.outcome}} == 'success'
         id: plan
         run: |
-          cd terraform/environments/${{inputs.tag}}
+          cd terraform/environments/${{inputs.environment}}
           terraform apply --auto-approve
